### ISSUE TITLE
Bug: Script fails to execute factory reset on the phone

### ISSUE THREAD

**Issue by ItzTrivial** [project-error/npwd#792] opened 2022-06-24 16:19 UTC
### Development Issue

Unsure

### Phone Version

master-branch

### Issue Description

When going to the settings on the phone and trying to factory reset the phone there is an error in the console. The animation of the ped holding the phone is still playing and the nui is still focused on the phone, the player being unable to punch etc. 

### Issue Reproduction

1 - Opening Phone
2 - Settings
3 - Factory reset
4 - Error in Console

### Evidence

![unknown](https://user-images.githubusercontent.com/66124070/175576178-1aab53ac-5244-4974-a436-55f6fc7e3202.png)

**Comment by Mojito-Fivem** [comment] 2022-06-25 16:21
Appears to be caused by this, since our atom has a default of null when we reset it gets assigned null instead of the default. https://github.com/project-error/npwd/blob/e16b533fa8688bf8d1ad1f65c601274771ba02e1/phone/src/apps/settings/state/settings.state.ts#L51-L55

**Comment by Mojito-Fivem** [comment] 2022-06-25 16:31
Fixed on develop branch 🙂

**Closed by Mojito-Fivem** 2022-06-25 16:31 UTC
Labels: New Issue
