### ISSUE TITLE
Enhancement: Call/messages export

### ISSUE THREAD

**Issue by Dennis-NL** [project-error/npwd#517] opened 2022-01-09 19:46 UTC
### Application

Contacts

### Dependency

No

### Feature Description

An export to create contacts
And an event to listen to messages or calls from certain numbers

This way it would be possible to create Police, Ambulance, Mechanic etc. contacts

**Comment by itschip** [comment] 2022-01-09 20:04
Duplicate of #479 

You can already fill in new contacts with exports. Read the documentation.

**Closed by itschip** 2022-01-09 20:04 UTC
Labels: Enhancement
