### ISSUE TITLE
Bug: Stuck rejected call in notification bar

### ISSUE THREAD

**Issue by Deniel00** [project-error/npwd#544] opened 2022-01-16 09:51 UTC
### Developement Issue

No

### Phone Version

v1.0.5

### Issue Description

If reject a call it will stuck into notification bar.

### Issue Reproduction

1. Wait for calling you
2. Reject incoming call
3. It will stuck into notification bar

### Evidence

![kép](https://user-images.githubusercontent.com/12788940/149655022-59514b94-1d45-4393-a018-ac4a43effa66.png)
```
[         script:npwd] [NPWD] [events] [silly]: { source: 61, data: { receiverNumber: '15059' } }
[         script:npwd] [NPWD] [calls] [debug]: Receiving Identifier: steam:11000
[         script:npwd] [NPWD] [calls] [debug]: Receiving source: 60 
[         script:npwd] [NPWD] [calls] [debug]: Call obj set with key 20810, value:
[         script:npwd] [NPWD] [calls] [debug]: {
[         script:npwd]   identifier: 'f447e61b-7d6a-4cf7-b8bb-aafa658b82bc',
[         script:npwd]   transmitter: '20810',
[         script:npwd]   transmitterSource: 61,
[         script:npwd]   receiver: '15059',
[         script:npwd]   receiverSource: 60,
[         script:npwd]   start: '1642176039',
[         script:npwd]   is_accepted: false
[         script:npwd] }
[         script:npwd] [NPWD] [events] [silly]: Response Promise Event npwd:beginCall:fdf9d345-54c1-4fc7-85ff-09a9c238a8ce (4.4796ms), Data >>
[         script:npwd] [NPWD] [events] [silly]: {
[         script:npwd]   status: 'ok',
[         script:npwd]   data: {
[         script:npwd]     is_accepted: false,
[         script:npwd]     transmitter: '20810',
[         script:npwd]     receiver: '15059',
[         script:npwd]     isTransmitter: true
[         script:npwd]   }
[         script:npwd] }
[         script:npwd] [NPWD] [events] [silly]: netPromise > npwd:fetchAllNotes > RequestObj
[         script:npwd] [NPWD] [events] [silly]: { source: 61, data: null }
[         script:npwd] [NPWD] [events] [silly]: Response Promise Event npwd:fetchAllNotes:7a6d9465-785f-4e70-b863-ecf11098b2b2 (1.0365ms), Data >>
[         script:npwd] [NPWD] [events] [silly]: { status: 'ok', data: [] }
```

**Comment by itschip** [comment] 2022-03-31 01:17
Duplicate of #696

**Closed by itschip** 2022-03-31 01:17 UTC
Labels: New Issue, Priority
