### ISSUE TITLE
Enhancement: Enable Photo Enlargement upon Clicking Image (Twitter, Marketplace, etc)

### ISSUE THREAD

**Issue by ch0sguy** [project-error/npwd#642] opened 2022-02-25 07:55 UTC
### Application

Twitter

### Dependency

No

### Feature Description

Similar to how qb-phone enlarges the image when the player selects it, it would be nice to implement this feature, especially in regards to twitter, as the resolution scales downward to display within app.

**Comment by itschip** [comment] 2022-02-25 07:59
Duplicate of #583

**Closed by itschip** 2022-02-25 07:59 UTC
Labels: Enhancement
