### ISSUE TITLE
Bug: Contacts loading

### ISSUE THREAD

**Issue by benzon** [project-error/npwd#239] opened 2021-05-21 15:52 UTC
**Describe the bug**
Contacts might not load as intended.

Have had this issue once, ill try and confirm it and reproduce, but looks like and issue maybe multichar related?

Where contacts dos not load before adding a new contact.

**Comment by itschip** [comment] 2021-05-21 20:48
Repro?

**Comment by benzon** [comment] 2021-05-21 22:11
Ill test it out abit later and see if it keeps happening.

**Comment by RockySouthpaw** [comment] 2021-05-22 03:12
Couldn't reproduce ether.

**Comment by itschip** [comment] 2021-05-24 00:43
Closing for now, because of no repro.

**Closed by itschip** 2021-05-24 00:43 UTC
Labels: New Issue, Unconfirmed
