### ISSUE TITLE
Bug: NUI Freezing While Calling

### ISSUE THREAD

**Issue by CloakedManz** [project-error/npwd#683] opened 2022-03-24 23:28 UTC
### Development Issue

Yes

### Phone Version

1.2.3

### Issue Description

When you make a phone call, when the other person answers, the phone continues to ring, and the NUI freezes. You are unable to hang up. This happens when you try to close the phone while calling someone. When you press backspace to close the phone, the NUI completely freezes.

### Issue Reproduction

Call someone
Press backspace to close the phone from your active item
NUI freezes, and continues to ring when the person answers

### Evidence

https://streamable.com/ef9cpj

**Comment by Mojito-Fivem** [comment] 2022-03-25 17:58
I'm unable to reproduce

**Comment by itschip** [comment] 2022-03-31 01:12
Fixed in develop.

**Closed by itschip** 2022-03-31 01:12 UTC
Labels: Information Needed, New Issue, Unconfirmed
