### ISSUE TITLE
Bug: Sending message to offline player causes the phone UI to brick and not work at all

### ISSUE THREAD

**Issue by 0pax** [project-error/npwd#310] opened 2021-08-28 22:04 UTC
**Is this issue related to the phone still being in development?**
Yes

**Describe the bug**
If you send a message to a player thats offline (in my case a contact), it will send a error message, but still 'send' the message. When re-entering the message app and trying to open the conversation again, the phone UI completely bricks, and you need to relog for it to work again. In the Dev Tools console it says:
"POST https://npwd/npwd:app:MESSAGES" 404 (Not Found)

**To Reproduce**
1. Go to the message app
2. Send a message to a offline player
3. Exit the message app
4. Re-enter the message app, and try to open the conversation with the offline player again

**Expected behavior**
The phone UI should brick and you won't be able to use the phone, and need to relog

**Evidence**
Just picture the phone being stuck on the screen and nothing else to do

**Needed information (please complete the following information):**
 - **Server OS**: Windows 10
- **Server Artifact version**: 4007
- What version of **new-phone-who-dis** are you running? Latest master

**Additional context**

**Comment by TasoOneAsia** [comment] 2021-08-28 22:14
Duplicate of #228, will change title to reflect message issue as well

**Closed by TasoOneAsia** 2021-08-28 22:14 UTC
Labels: New Issue
