### ISSUE TITLE
Bug: onMessage export errors

### ISSUE THREAD

**Issue by AvaN0x** [project-error/npwd#592] opened 2022-02-07 21:46 UTC
### Development Issue

Yes

### Phone Version

Release 1.1.5

### Issue Description

It's seem that we can only have one listener on message with this exports for the same number, if you set two `onMessage` listener on the same number, only the last one will be used.
There is also an error if you stop the resource that was listening to a number.

### Issue Reproduction

1. Create a simple listener inside of a script : 
  ```lua
  exports.npwd:onMessage("911", function(ctx)
  end)
  ```
2. Send a message to the number `911`, there will be no error
1. Stop the script that has the listener above
1. Send a new message and you will see this error : 
![image](https://user-images.githubusercontent.com/27494805/152875591-cc9951b3-a38f-4b32-be55-7858170e2029.png)

### Idea to fix

I think the easiest way to fix this could be to use events ?
If you want to listen you would have to use : 
```lua
AddEventHandler("npwd:onMessage:911", function(ctx)
end)

-- And the export code
function onMessage(number, cb)
   AddEventHandler("npwd:onMessage:" .. number, cb)
end
```
This would be triggered every time a message is sent.

If you don't want every message to call the event, you could make the export save which numbers should trigger it. Something like :
```lua
function onMessage(number, cb)
   -- Save the number to be listened somewhere
   AddEventHandler("npwd:onMessage:" .. number, cb)
end
```
and only trigger the event if the event is set as listened.
*(I know the snippet here are in lua, it's just to give an idea of what I imagine)*

**Comment by RockySouthpaw** [comment] 2022-02-08 01:02
This is entirely not true. Furthermore, exports will break because you restarted the resource that was calling the export. You need to wrap it in a resource start handler. 

Also, why would you use a listener for the same number twice???

Here is working psudo code:
```lua
AddEventHandler('onResourceStart', function(resourceName)
	if resourceName == 'npwd' then
		for i = 1, #Config.emergencyNumbers do
            local number = Config.emergencyNumbers[i]
            exports.npwd:onMessage(number, function(ctx)
                print('Target Number: ['..ctx.data.tgtPhoneNumber..'] Message: ['..ctx.data.message..'] From: ['..ctx.source..']')

            end)
        end
	end
end)
```

**Comment by AvaN0x** [comment] 2022-02-08 07:43
> This is entirely not true in regards to only being able to listen to one number.

Oh this is not what I meant sorry. I was talking about having one per number.

> Also, why would you use a listener for the same number twice???

To be honest I won't need this myself, just figured out that it *could* be useful to somebody.

> Furthermore, exports will break because you restarted the resource that was calling the export. You need to wrap it in a resource start handler.

I tried this, but as I thought this do not seem to be fixing the issue. To me, it is because npwd still holds the function reference from the script that got stopped/restarted and tries to call it.
![image](https://user-images.githubusercontent.com/27494805/152940374-7a52da20-58b5-40cd-a82b-9f4610d66bcc.png)
One way to fix it could also be to save which resource is listening to the number, and if this one get stopped, remove the function reference ?

**Comment by AvaN0x** [comment] 2022-02-08 21:34
> I am unable to reproduce this. Works just fine when restarting a resource utilizing the 'onMessage' export, or moving the export to another resource.

Can you try to totally remove the export from the resource you restarted or stop the resource ?

**Comment by AvaN0x** [comment] 2022-02-08 21:55
Ok here are some steps to do it : (Release 1.1.5)
1. Download this resource
[npwd_issue_592.zip](https://github.com/project-error/npwd/files/8027714/npwd_issue_592.zip)
It only calls the `onMessage` export for the number `911`
1. Start the resource `ensure npwd_issue_592`
1. Send a message to `911`, here I sent `test`
![image](https://user-images.githubusercontent.com/27494805/153082143-1320bfce-631e-4fc8-b8a5-e0ba2409c595.png)
1. Stop the resource `stop npwd_issue_592`
1. Send another message to `911`, here I sent `test` again
![image](https://user-images.githubusercontent.com/27494805/153082186-bca2e970-d901-4258-9932-6b30bea20d96.png)

**Comment by itschip** [comment] 2022-02-08 22:06
@AvaN0x Can you please test this from the 'master' branch?

**Comment by AvaN0x** [comment] 2022-02-08 22:20
I just tried, I have the more detailed error log you added in [in the last commit](https://github.com/project-error/npwd/commit/e4b731a6cce404f32ed64c8be49d169879e37c68).
![image](https://user-images.githubusercontent.com/27494805/153085211-2aa1c11a-9f48-4feb-a95e-817ed651e38c.png)

**Comment by itschip** [comment] 2022-02-08 22:22
Ah, got confused since you wrote `Ok here are some steps to do it : (Release 1.1.5)` :/

**Comment by itschip** [comment] 2022-02-08 22:23
Either way, would be nice if someone else could verify this as well.

**Comment by RockySouthpaw** [comment] 2022-02-09 01:16
> Either way, would be nice if someone else could verify this as well.
It’s an edge case scenario. You can reproduce this with `npwd-addons` and restarting the resource.

This is a non issue. **Literally just restart the resource + phone.**

**Comment by itschip** [comment] 2022-02-10 07:39
> This is a non issue. Literally just restart the resource + phone.

You just need to restart the resource that is using whatever export. I'll update the error message, and close this.

**Comment by RockySouthpaw** [comment] 2022-02-11 02:51
![image](https://user-images.githubusercontent.com/55056068/153530502-7b76ab54-1da2-48fa-a05e-e6fae761cd4b.png)
Resolved

**Closed by RockySouthpaw** 2022-02-11 02:51 UTC

**Comment by AvaN0x** [comment] 2022-02-11 07:35
> ![image](https://user-images.githubusercontent.com/55056068/153530502-7b76ab54-1da2-48fa-a05e-e6fae761cd4b.png)
> Resolved

Nice thank you
