### ISSUE TITLE
Bug(Messages): Conversation list doesnt save

### ISSUE THREAD

**Issue by 0pax** [project-error/npwd#435] opened 2021-12-23 18:52 UTC
### Developement Issue

Yes

### Phone Version

Dev branch, downloaded yesterday after the ESX fix.

### Issue Description

When sending messages to other players, the conversation list stays until you relog. So when you've logged out and log in again, the whole conversation list disappears. But if you enter the conversation, the messages are stil there.

### Issue Reproduction

1. Open phone
2. Route to messages
3. Start a conversation with a valid phone number. (They can be online or offline.)
4. Send a text within said conversation.
5. F8 Quit
6. Relog into the server on the same character as before.

The conversation you created doesn’t display however, the database does have the message. So if you send a message to the number again, the existing text will be shown.

**Comment by RockySouthpaw** [comment] 2021-12-23 18:54
The message saves in the DB, it just isn’t fetched it seems

**Comment by itschip** [comment] 2021-12-23 18:55
Please provide a video or detailed reproduction steps.

**Comment by RockySouthpaw** [comment] 2021-12-23 19:01
> Please provide a video or detailed reproduction steps.

1. Open phone
2. Route to messages
3. Start a conversation with a valid phone number. (They can be online or offline.)
4. Send a text within said conversation.
5. F8 Quit
6. Relog into the server on the same character as before.

The conversation you created doesn’t display however, the database does have the message. So if you send a message to the number again, the existing text will be shown.

**Comment by itschip** [comment] 2021-12-24 21:25
@RockySouthpaw @0pax Check if f6183b97e1510f59dcf28af5fc02795233cd7c56 in 'develop' fixes the issue.

**Comment by 0pax** [comment] 2021-12-24 21:26
> @RockySouthpaw @0pax Check if [f6183b9](https://github.com/project-error/npwd/commit/f6183b97e1510f59dcf28af5fc02795233cd7c56) in 'develop' fixes the issue.

Will check when I’m home in about 20-30 minutes.

**Comment by 0pax** [comment] 2021-12-24 22:37
Hey @itschip , I've tested the changes, the conversation list appears, just without contact name or number, and when entering the conversation you get an error message.
Images below:
https://cdn.upload.systems/uploads/rckq7naY.png
https://cdn.upload.systems/uploads/VzapC3QC.png
https://cdn.upload.systems/uploads/AaCtv6w3.png

**Comment by itschip** [comment] 2021-12-24 22:41
@0pax Pushed a new possible fix in develop now,

**Comment by 0pax** [comment] 2021-12-24 22:42
> @0pax Pushed a new possible fix in develop now,

Alright, let me test.

**Comment by RockySouthpaw** [comment] 2021-12-24 22:43
As far as the contact name not showing when you first open, this is intended currently with how lazy fetching works.

**Comment by 0pax** [comment] 2021-12-24 22:45
> As far as the contact name not showing when you first open, this is intended currently with how lazy fetching works.

My bad =P

**Comment by TasoOneAsia** [comment] 2021-12-24 22:46
> this is intended currently with how lazy fetching works. 

Not necessarily an "intended feature", but something that would require a change at the architecture level for how apps are defined and initialized. Open to thoughts.

**Comment by RockySouthpaw** [comment] 2021-12-24 22:52
> > this is intended currently with how lazy fetching works.
> 
> Not necessarily an "intended feature", but something that would require a change at the architecture level for how apps are defined and initialized. Open to thoughts.

We should probs open an issue regarding it tbh

**Comment by itschip** [comment] 2021-12-24 22:54
This issues should be fixed, but could someone confirm?

**Comment by itschip** [comment] 2021-12-25 11:02
This seems to have been fixed. Let's open a new issue regarding app initialization.

**Closed by itschip** 2021-12-25 11:02 UTC
Labels: New Issue
