### ISSUE TITLE
Bug: emitMessage doesn't work when the conversation does not exist

### ISSUE THREAD

**Issue by pierrearma** [project-error/npwd#736] opened 2022-04-27 15:15 UTC
### Development Issue

Unsure

### Phone Version

1.2.95

### Issue Description

If we use the export "emitMessage" and the conversation does not exist, an error occur.

`Failed to emit message. Error: Cannot read properties of undefined (reading 'id')`

### Issue Reproduction

1. Be sure not to have a conversation with 912 (you can put the number you want).
2. Execute this code

  ```lua
  exports.npwd:emitMessage({
      senderNumber = '912',
      targetNumber = PUT_YOUR_PHONE_NUMBER_HERE,
      message = 'JUJUJUL'
  })
  ```

4. Error : `Failed to emit message. Error: Cannot read properties of undefined (reading 'id')`
5. Now create a conversation with 912 (by sending a message)
6. Executes the code again
7. It works!

**Comment by itschip** [comment] 2022-04-27 15:18
@pierrearma is this a group chat, or a 1-to-1 conversation?

**Comment by pierrearma** [comment] 2022-04-27 15:19
> @pierrearma is this a group chat, or a 1-to-1 conversation?

I tested with a 1-to-1 conversation. Between me and 912.

**Comment by itschip** [comment] 2022-04-27 15:20
@pierrearma so I assume that this '921' is not an actual user in the db? If not , can you try with an actual user? The issue is most likely that we can't find the user.

**Comment by itschip** [comment] 2022-04-27 15:21
Oh
>Executes the code again
It works!

**Comment by itschip** [comment] 2022-04-27 15:22
Ah, so I guess we'll just have to create an conversation automatically if it doesn't exist then @Mojito-Fivem

**Comment by pierrearma** [comment] 2022-04-27 15:24
> @pierrearma so I assume that this '921' is not an actual user in the db? If not , can you try with an actual user? The issue is most likely that we can't find the user.

No it is already managed in the code the fact that the player is not found and it works.

> Ah, so I guess we'll just have to create an conversation automatically if it doesn't exist then @Mojito-Fivem

Yes I think it's just that.

**Comment by Mojito-Fivem** [comment] 2022-04-27 17:15
Potentially fixed on develop with 78b4a1321565e405fe3b0385fb562f800b795817

**Comment by pierrearma** [comment] 2022-04-27 18:18
@Mojito-Fivem  I built the phone myself on the develop branch and there seems to be a problem on the frontend.
The notification is frozen (can't click on it, can't close it) and the conversation doesn't appear in the app.
When I restart the phone, the conversation appear.

**Comment by Mojito-Fivem** [comment] 2022-04-27 19:19
6ee12137c2d369bdcabb60a5ab7cd269a7d3bdc1 Should fix that fingers crossed

**Comment by pierrearma** [comment] 2022-04-27 19:28
It's fixed for me. You can close the issue when you want.

**Closed** 2022-04-27 19:45 UTC
Labels: Verified Issue
