### ISSUE TITLE
Bug: user_identifier not populated when sending messages

### ISSUE THREAD

**Issue by AceScottie** [project-error/npwd#340] opened 2021-11-18 22:50 UTC
### Developement Issue

Yes

### Issue Description

error: Field 'user_identifier' doesn't have a default value
I defaulted that value to see if it magically fixes it and checked the db.
| id | message | user_identifier | conversation_id
|  1 | Hello   |      | char1:71e008fe139deedc849b862e33c9bcecbf8f959b+char1:d1c9463e8c6c3bfa3b915dce2380b5f04bf61d04 | 
so in this case my identifier is being found as char1:d1c9463e8c6c3bfa3b915dce2380b5f04bf61d04 |
the destination identifier is char1:71e008fe139deedc849b862e33c9bcecbf8f959b
but its not putting either in the user_identifier column.

### Issue Reproduction

Built from github on debian 10.
1: installed yarn and nodejs from apt using:
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update && apt-get upgrade
curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
apt-get install -y nodejs

2a: cd /root/txData/server/resources
2b: git clone https://github.com/project-error/npwd
2c: cd npwd/
3: yarn
4: yarn build
5: touch .yarn.installed
6: edit config.json for multi chars
7: restarted server and ingame tried to send a message

### Evidence

[         script:npwd] [NPWD] [messages] [error]: Failed to send message, Field 'user_identifier' doesn't have a default value
[         script:npwd] [NPWD] [events] [silly]: netPromise > npwd:fetchMessages > RequestObj
[         script:npwd] [NPWD] [events] [silly]: {
[         script:npwd]   source: 1,
[         script:npwd]   data: {
[         script:npwd]     conversationId: 'char1:71e008fe139deedc849b862e33c9bcecbf8f959b+char1:d1c9463e8c6c3bfa3b915dce2380b5f04bf61d04',
[         script:npwd]     page: 0
[         script:npwd]   }
[         script:npwd] }

**Comment by RockySouthpaw** [comment] 2021-11-19 06:28
What version of mysql are you using? 

This occurred when testing the latest messages refactor, but wasn’t able to be reproduced by chip so it was merged. I theorized that the issue is related to mysql versions where chip is using Maria DB and I use Mysql 8 while encountering this same issue. Not sure if it’s the case though, just a theory.

You can try setting the default for that column to null within your sql to see if that fixes the error.

**Comment by AceScottie** [comment] 2021-11-19 09:18
mysql  Ver 15.1 Distrib 10.5.12-MariaDB, for debian-linux-gnu

https://github.com/project-error/npwd/blob/6631efa46866c69ae66247cdbfac7f0ef03aa557/resources/server/messages/messages.db.ts#L17
`INSERT INTO npwd_messages (author, message, conversation_id)`
this line does not include the user_identifier and is the only refrence to npwd_messages i can find. The import.sql adds the column as NOT NULL but with no default.
looking through the select from npwd_messages it seems this column isnt actually used at all.

**Comment by itschip** [comment] 2021-11-19 09:27
👍🏻 I'll fix it this weekend

**Comment by RockySouthpaw** [comment] 2021-11-22 00:28
@itschip Issue still exist as of commit https://github.com/project-error/npwd/pull/350 on master

**Comment by RockySouthpaw** [comment] 2021-11-23 05:59
@AceScottie So did you encounter issues when creating the intial group?

**Closed** 2021-12-01 00:20 UTC
Labels: New Issue
