### ISSUE TITLE
Enhancement: Mod Message delete option

### ISSUE THREAD

**Issue by Dennis-NL** [project-error/npwd#858] opened 2022-08-28 17:30 UTC
### Application

Other

### Dependency

No

### Feature Description

Option for moderators to delete Tweets, Marketplace ads and matchmaking profiles

Now we have to remove them from database. 
But it would be much easier to moderate when we have a delete button next to the messages/ads

**Comment by itschip** [comment] 2022-08-28 17:32
Duplicate of #848

**Closed by itschip** 2022-08-28 17:32 UTC
Labels: Enhancement
