### ISSUE TITLE
Bug: Twitter Emojis are not showing once posted

### ISSUE THREAD

**Issue by PERPGamer** [project-error/npwd#468] opened 2022-01-02 23:09 UTC
### Developement Issue

Unsure

### Phone Version

1.0.3

### Issue Description

On the Twitter app, once you post a message with an emoji, the emoji shows as a question mark (?).

### Issue Reproduction

  1. Go to 'Twitter'
  2. Post a message on Twitter with an emoji.
  3. See ? instead of emoji

### Evidence

Before post/tweet:
![image](https://user-images.githubusercontent.com/13124880/147891858-9580d19f-9eb9-44a3-9a48-073f4bf83e75.png)

After posted/tweeted:
![image](https://user-images.githubusercontent.com/13124880/147891861-b538e65d-d153-47dd-a61d-87c367840707.png)

**Comment by RockySouthpaw** [comment] 2022-01-03 01:09
Will check in about 20 monutss

**Comment by ChatDisabled** [comment] 2022-01-03 06:58
Can confirm, had the same thing when I had to test the QBCore wrapper. Thought it would be a one time thing. But since you posted the same guess I will show my face.

**Comment by RockySouthpaw** [comment] 2022-01-03 07:17
Are you both on qbcore?

**Comment by RockySouthpaw** [comment] 2022-01-03 07:20
Also I can’t reproduce this issue. Need the server console logs for this.

**Comment by itschip** [comment] 2022-01-03 07:26
@ChatDisabled @PERPGamer What is your table collation?

**Comment by RockySouthpaw** [comment] 2022-01-03 07:26
> Can confirm, had the same thing when I had to test the QBCore wrapper. Thought it would be a one time thing. But since you posted the same guess I will show my face.

Also in the future if you test something and encounter an issue, it’s good practice to bring up said issue *regardless* if you think it’s a “me” issue. Never hurts to say anything.

**Comment by ChatDisabled** [comment] 2022-01-03 07:39
If talking about the QBCore specific DB settings, everything is installed as needed. Thing is, if displayed in txAdmin it looks fine.

[         script:npwd] [NPWD] [events] [silly]: netPromise > npwd:createTweet > RequestObj
[         script:npwd] [NPWD] [events] [silly]: {
[         script:npwd]   source: 1,
[         script:npwd]   data: { images: '', message: 'Noice 😗😗 👮', retweet: null }
[         script:npwd] }
[         script:npwd] [NPWD] [events] [silly]: Response Promise Event npwd:createTweet:82328b95-5462-4b40-9616-61d760b984d2 (12.2746ms), Data >>
[         script:npwd] [NPWD] [events] [silly]: { status: 'ok' }

But of course when displayed in game through the phone.

![image](https://user-images.githubusercontent.com/44729807/147908051-42fc7f52-3bd5-43d7-97af-099064f76925.png)

Just tell me which console prints you want or if I need to set me debug on a certain mode. I'm not good in this kind of thing if you ask me general questions :s. Hence why I don't report me problems or otherwise I just get dumped into the ground for not knowing.

**Comment by TasoOneAsia** [comment] 2022-01-03 17:38
This is most likely due to the character set of your database? NPWD will just use the default, if the chosen character set does not support emoji encoding this is what happens.

**Comment by ChatDisabled** [comment] 2022-01-03 20:03
Ah that collation. As the interwebs stated after changing it too `utf8mb4_bin` it indeed resolved the issue. So it was a me problem 😝. If @PERPGamer could confirm it as well.

**Comment by TasoOneAsia** [comment] 2022-01-03 21:20
I'll close this issue for now considering that is the most probable reason.

**Closed** 2022-01-03 21:20 UTC
Labels: Information Needed, Unconfirmed

**Comment by PERPGamer** [comment] 2022-01-03 22:00
> Ah that collation. As the interwebs stated after changing it too `utf8mb4_bin` it indeed resolved the issue. So it was a me problem 😝. If @PERPGamer could confirm it as well.

This did fix it, thank you everyone 😄
