### ISSUE TITLE
Bug: Messages not being created / sent

### ISSUE THREAD

**Issue by Agimir** [project-error/npwd#542] opened 2022-01-16 00:57 UTC
### Developement Issue

No

### Phone Version

1.0.5

### Issue Description

While player has phone number (or contact) and is trying to message another player via the messaging app, the app bring the player to the search bar and when they enter either the contact name or the number and press enter, nothing happens on pressing or clicking enter. 

### Issue Reproduction

1- Click on message
2- Click on "+" to create new message
3- Search for contact in search bar OR enter player number
4- Press enter OR click send

No result

### Evidence

Below is a message from the console

![1_npwd](https://user-images.githubusercontent.com/57418247/149643104-eda1b18a-c997-4b3f-bfee-99a1f8d24732.PNG)

**Comment by RockySouthpaw** [comment] 2022-01-16 00:58
Cant reproduce. Did you run the sql?

**Comment by Agimir** [comment] 2022-01-16 01:03
Yes I did. I can actually see the messages being created in the npwd_messages_conversations, but the npwd_messages in the DB remain empty.

![image](https://user-images.githubusercontent.com/57418247/149643330-dcc92f77-3ec2-44b0-adf3-33fb364cc779.png)

**Comment by RockySouthpaw** [comment] 2022-01-16 03:51
> Yes I did. I can actually see the messages being created in the npwd_messages_conversations, but the npwd_messages in the DB remain empty.
> 
> note*: We already had a phone_number column for our user table, but it is a VARCHAR 10 instead of 20.
> 
> ![image](https://user-images.githubusercontent.com/57418247/149643330-dcc92f77-3ec2-44b0-adf3-33fb364cc779.png)

You should make this varchar20 in the event NPWD does generate a phone number. Though idk what framework you’re using so you probably don’t use our generation.

This bug doesn’t quite make sense because the participant identifier is the source number too

**Comment by Agimir** [comment] 2022-01-16 08:16
I did try changing it and I found these two error messages:
![image](https://user-images.githubusercontent.com/57418247/149652399-708e19e5-445e-4c4a-86d4-12f0d3dfcb42.png)

![image](https://user-images.githubusercontent.com/57418247/149652416-b111aa5e-3b3b-4e8e-a9da-1fc40a0615ac.png)

I am going to try the overextended module for esx. We are running legacy right now, but it did generate a new number in the correct format (i.e. ###-###-####)

**Comment by itschip** [comment] 2022-01-16 09:06
You'll have to change your collations throughout your tables. I recommend just using `utf8mb4_general_ci`

**Comment by Agimir** [comment] 2022-01-16 15:28
> 

How would I go about just using utf8mb4_general_ci?

**Comment by RockySouthpaw** [comment] 2022-01-16 23:33
> How would I go about just using utf8mb4_general_ci or changing my collations in my tables?

Just update your entire database to this

**Comment by Sky3Dox** [comment] 2022-01-17 03:36
I have the same issue. I think multicharacter system is creating a problem with this?

**Comment by RockySouthpaw** [comment] 2022-01-17 03:42
No.

**Comment by Sky3Dox** [comment] 2022-01-17 05:03
Okay.. have you found a solution though? I'm running OX ESX

**Comment by Agimir** [comment] 2022-01-17 05:23
So, what I did was:
1- drop all the tables for the NPWD resource in the DB
2- Uploaded the new version that came out today and inserted the SQL
3- I then went into the SQL and used this to edit the tables pertaining to the messages

ALTER TABLE npwd_messages CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE npwd_messages_conversationsCONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;

That is what made it work for me. I can send messages to other players now. If it does not work for you, I'm not sure what else to suggest other than look through the git here and ask the dev for help.

**Comment by Sky3Dox** [comment] 2022-01-17 05:52
I will try it and let you know if it works for me!

**Comment by Sky3Dox** [comment] 2022-01-17 06:35
That actually worked! Thanks man..

**Comment by itschip** [comment] 2022-01-17 09:40
@Agimir @Sky3Dox Can I close this?

**Comment by Agimir** [comment] 2022-01-17 15:54
@itschip Yes, thank you very much for the help!

**Closed** 2022-01-17 17:39 UTC
Labels: New Issue
