### ISSUE TITLE
Bug: Contacts transfer over after unload

### ISSUE THREAD

**Issue by AvarianKnight** [project-error/npwd#315] opened 2021-09-18 14:30 UTC
**Describe the bug**
When a character unloads, they don't get an event to 'reset' their contacts, this leads to them keeping their old contacts due to the atom already being populated

**Expected behavior**
On unload the contacts atom (and other atoms) be reset and re-fetch on next phone open

**Comment by RockySouthpaw** [comment] 2021-10-02 01:00
I wasn't able to reproduce this since contacts is broken on dev with multi char. Can you check if their phone number is being changed in settings? I would imagine we probably need an unload event that can be sent since the phone inits when player joins.

**Comment by RockySouthpaw** [comment] 2021-11-02 21:06
Reproduced. Still valid as of https://github.com/project-error/npwd/commit/4e785c119efdc4944426d57d948ebd0635890c19

**Comment by RockySouthpaw** [comment] 2021-11-02 21:18
Steps to reproduction:
1. Create a contact on Character 1
2. Create a contact Character 2
3. Ensure NPWD
4. Ensure your framework or relog (otherwise contacts will return null for getPhoneNumber)
5. Upon loading, your contacts will have merged.

**Note:**
This isn't related to a lack of unloading for me What happens is contacts are based off identifier rather than the players phone number. So all contacts are the same. Wouldn't be an issue if the identifier column was like `char1:*` or something similar where the identifier isn't the same.

**Comment by thelindat** [comment] 2021-11-02 21:40
> 
> 
>  Wouldn't be an issue if the identifier column was like `char1:*` or something similar where the identifier isn't the same.

This is the type of multicharacter I use, however it's an issue since the NUI doesn't know to update contacts. On resource start it sends a request to the server to retrieve contact data, rather than the server sending contact data once the client has loaded.

**Comment by TasoOneAsia** [comment] 2021-11-21 01:06
This should be solved in releases following #334's patch.

**Closed** 2021-12-30 09:12 UTC
Labels: Verified Issue, Priority
