### ISSUE TITLE
Bug: new messages insert top of conversation

### ISSUE THREAD

**Issue by Deniel00** [project-error/npwd#685] opened 2022-03-26 17:35 UTC
### Development Issue

No

### Phone Version

1.2.3

### Issue Description

Sometimes new messages insert top of conversation

### Issue Reproduction

i'm dont know how reproducte, we're using phone script on prod server with 130+ players

### Evidence

database:
![kép](https://user-images.githubusercontent.com/12788940/160250889-48af4e2f-c505-4bbc-839b-7ef0e7fae131.png)
in phone first 5 message is the newest in database
![kép](https://user-images.githubusercontent.com/12788940/160250903-ed51fdfd-f77b-4c84-903b-d711027f1a36.png)

**Comment by Mojito-Fivem** [comment] 2022-03-26 17:37
I have no idea what im looking at, can you describe your issue better and provide a reproduction

**Comment by Deniel00** [comment] 2022-03-26 18:26
First 5 messages is the newest and 6. is the oldest. New messages pushed top of conservatin instead of bottom.
![kép](https://user-images.githubusercontent.com/12788940/160252443-fc72f674-1161-4043-b094-2dd381011f6a.png)
(purple highlights is newset, blue is oldest)

**Comment by itschip** [comment] 2022-03-26 18:33
Not totally sure, but likely that your primary key auto_inc value wasn't 0, and now when you've updated, the auto_inc value has been set to 0, but we should probably order messages by `createdAt` anyways.

**Comment by Deniel00** [comment] 2022-03-26 18:37
Messages id correct i'm think, because oldest id is 49 and newest 2570

**Comment by Deniel00** [comment] 2022-03-28 13:35
In v1.2.6 is still present.
last_message_id not update on new messages
![kép](https://user-images.githubusercontent.com/12788940/160407683-629e1f4c-cfbb-4db7-97fd-08830a0ea9bd.png)
![kép](https://user-images.githubusercontent.com/12788940/160407794-ceb04782-4b86-4eb2-acfd-cf653714bdf9.png)
and new messages pop top of first message
![error](https://user-images.githubusercontent.com/12788940/160408994-30d4f992-9b30-4d16-8374-0e6847bc1334.jpg)
![kép](https://user-images.githubusercontent.com/12788940/160408777-ed442249-3957-46a8-a500-79c7b3d9649b.png)
(you can see scroll bar)

**Comment by itschip** [comment] 2022-03-28 16:51
Thanks, I'll look into it.

**Comment by itschip** [comment] 2022-03-28 20:50
First issue should be fixed in https://github.com/project-error/npwd/commit/009b2ece551eaa6420d0cc9d8b97ea139e53daec

The rest is duplicate of #673

**Comment by Deniel00** [comment] 2022-03-29 08:46
i'm updated phone to 1.2.7. as soon as possible feedback about this issue (also https://github.com/project-error/npwd/issues/673)

**Comment by Deniel00** [comment] 2022-03-29 17:41
New information from players:
After 20 messages broke message order.
So 21th message will show of conservation top and shows those in subsequent order. It’s like having a new page after 20th message and putting it on top of it.

**Comment by Deniel00** [comment] 2022-03-29 17:59
video:
https://streamable.com/r6m4gt
test converstaion db:
![kép](https://user-images.githubusercontent.com/12788940/160674546-5e158fac-6d68-4d74-a955-31a8b837ac1d.png)

**Comment by itschip** [comment] 2022-03-30 13:03
Ill look into it.

**Comment by itschip** [comment] 2022-03-30 20:57
Fixed in develop. Closing for now.

**Closed by itschip** 2022-03-30 20:57 UTC
Labels: Information Needed, New Issue, Unconfirmed
